---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Inhalte
- type: directory
  path: content/aktivitaeten
  label: Aktivitäten
  create: documents
  match: "**/*"
- type: directory
  path: content/media
  label: Media
  create: documents
  match: "**/*"
- type: document
  path: content/mitmachen.md
  label: Mitmachen
- type: document
  path: content/kontakt.md
  label: Kontakt
- type: heading
  label: Einstellungen
- type: document
  path: static/navigation.json
  label: Navigation
upload_dir: static/media
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
