---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Inhalt
- type: directory
  path: content
  label: Seiten
  create: all
  match: "**/*.md"
  templates:
  - seite
- type: directory
  path: config/slideshows
  label: Slideshows
  create: documents
  match: "**/*"
  exclude: "*.json"
  new_doc_ext: json
  templates:
  - slideshow
- type: heading
  label: Einstellungen
- type: document
  path: config/navigation/main.json
  label: Hauptnavigation
  templates:
  - menuliste
- type: document
  path: config/navigation/footer.json
  label: Footer
  templates:
  - footer
upload_dir: static/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
